service: rebasebot-serverless

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GITHUB_TOKEN: "${self:custom.secrets.GITHUB_TOKEN}"
    GITHUB_LOGIN: "${self:custom.secrets.GITHUB_LOGIN}"
    WEBHOOK_SECRET: "${self:custom.secrets.WEBHOOK_SECRET}"

package:
  exclude:
    - secrets.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

functions:
  rebasebot:
    handler: handler.rebasebot
    events:
      - http:
          path: /webhook
          method: post